### ISSUE TITLE
Add e wallet for Donation

### ISSUE THREAD

**Issue by alfianriv** [raihan71/vue-mosque#3]
Please add e wallet for donation,

i can help but i need api e wallet gateway for contributing. You can reply in here.

**Comment by raihan71** [comment]
ok sure, I'll take a look for the API gateway first

**Comment by raihan71** [comment]
> Please add e wallet for donation,
> 
> i can help but i need api e wallet gateway for contributing. You can reply in here.

hey man, can you add the sandbox first just for example
